// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExchangeProperties exchange properties
//
// swagger:model ExchangeProperties
type ExchangeProperties struct {

	// auto delete
	AutoDelete bool `json:"auto_delete,omitempty"`

	// durable
	Durable bool `json:"durable,omitempty"`

	// internal
	Internal bool `json:"internal,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ExchangeProperties) UnmarshalJSON(data []byte) error {
	var props struct {

		// auto delete
		AutoDelete bool `json:"auto_delete,omitempty"`

		// durable
		Durable bool `json:"durable,omitempty"`

		// internal
		Internal bool `json:"internal,omitempty"`

		// type
		Type string `json:"type,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.AutoDelete = props.AutoDelete
	m.Durable = props.Durable
	m.Internal = props.Internal
	m.Type = props.Type
	return nil
}

// Validate validates this exchange properties
func (m *ExchangeProperties) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this exchange properties based on context it is used
func (m *ExchangeProperties) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExchangeProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExchangeProperties) UnmarshalBinary(b []byte) error {
	var res ExchangeProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
