// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"sbp/internal/transport/pay/models"
)

// NewGetQrParams creates a new GetQrParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetQrParams() *GetQrParams {
	return &GetQrParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetQrParamsWithTimeout creates a new GetQrParams object
// with the ability to set a timeout on a request.
func NewGetQrParamsWithTimeout(timeout time.Duration) *GetQrParams {
	return &GetQrParams{
		timeout: timeout,
	}
}

// NewGetQrParamsWithContext creates a new GetQrParams object
// with the ability to set a context for a request.
func NewGetQrParamsWithContext(ctx context.Context) *GetQrParams {
	return &GetQrParams{
		Context: ctx,
	}
}

// NewGetQrParamsWithHTTPClient creates a new GetQrParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetQrParamsWithHTTPClient(client *http.Client) *GetQrParams {
	return &GetQrParams{
		HTTPClient: client,
	}
}

/*
GetQrParams contains all the parameters to send to the API endpoint

	for the get qr operation.

	Typically these are written to a http.Request.
*/
type GetQrParams struct {

	// Body.
	Body *models.GetQr

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get qr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQrParams) WithDefaults() *GetQrParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get qr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQrParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get qr params
func (o *GetQrParams) WithTimeout(timeout time.Duration) *GetQrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get qr params
func (o *GetQrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get qr params
func (o *GetQrParams) WithContext(ctx context.Context) *GetQrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get qr params
func (o *GetQrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get qr params
func (o *GetQrParams) WithHTTPClient(client *http.Client) *GetQrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get qr params
func (o *GetQrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get qr params
func (o *GetQrParams) WithBody(body *models.GetQr) *GetQrParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get qr params
func (o *GetQrParams) SetBody(body *models.GetQr) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetQrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
