// Code generated by go-swagger; DO NOT EDIT.

package washes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewAssignWashToGroupParams creates a new AssignWashToGroupParams object
//
// There are no default values defined in the spec.
func NewAssignWashToGroupParams() AssignWashToGroupParams {

	return AssignWashToGroupParams{}
}

// AssignWashToGroupParams contains all the bound params for the assign wash to group operation
// typically these are obtained from a http.Request
//
// swagger:parameters assignWashToGroup
type AssignWashToGroupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	GroupID strfmt.UUID
	/*
	  Required: true
	  In: path
	*/
	WashID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAssignWashToGroupParams() beforehand.
func (o *AssignWashToGroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGroupID, rhkGroupID, _ := route.Params.GetOK("groupId")
	if err := o.bindGroupID(rGroupID, rhkGroupID, route.Formats); err != nil {
		res = append(res, err)
	}

	rWashID, rhkWashID, _ := route.Params.GetOK("washId")
	if err := o.bindWashID(rWashID, rhkWashID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGroupID binds and validates parameter GroupID from path.
func (o *AssignWashToGroupParams) bindGroupID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("groupId", "path", "strfmt.UUID", raw)
	}
	o.GroupID = *(value.(*strfmt.UUID))

	if err := o.validateGroupID(formats); err != nil {
		return err
	}

	return nil
}

// validateGroupID carries on validations for parameter GroupID
func (o *AssignWashToGroupParams) validateGroupID(formats strfmt.Registry) error {

	if err := validate.FormatOf("groupId", "path", "uuid", o.GroupID.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindWashID binds and validates parameter WashID from path.
func (o *AssignWashToGroupParams) bindWashID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("washId", "path", "strfmt.UUID", raw)
	}
	o.WashID = *(value.(*strfmt.UUID))

	if err := o.validateWashID(formats); err != nil {
		return err
	}

	return nil
}

// validateWashID carries on validations for parameter WashID
func (o *AssignWashToGroupParams) validateWashID(formats strfmt.Registry) error {

	if err := validate.FormatOf("washId", "path", "uuid", o.WashID.String(), formats); err != nil {
		return err
	}
	return nil
}
