// Code generated by go-swagger; DO NOT EDIT.

package washes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"sbp/openapi/models"
)

// DeleteWashNoContentCode is the HTTP code returned for type DeleteWashNoContent
const DeleteWashNoContentCode int = 204

/*
DeleteWashNoContent OK

swagger:response deleteWashNoContent
*/
type DeleteWashNoContent struct {
}

// NewDeleteWashNoContent creates DeleteWashNoContent with default headers values
func NewDeleteWashNoContent() *DeleteWashNoContent {

	return &DeleteWashNoContent{}
}

// WriteResponse to the client
func (o *DeleteWashNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

func (o *DeleteWashNoContent) DeleteWashResponder() {}

/*
DeleteWashDefault Generic error response

swagger:response deleteWashDefault
*/
type DeleteWashDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWashDefault creates DeleteWashDefault with default headers values
func NewDeleteWashDefault(code int) *DeleteWashDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteWashDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete wash default response
func (o *DeleteWashDefault) WithStatusCode(code int) *DeleteWashDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete wash default response
func (o *DeleteWashDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete wash default response
func (o *DeleteWashDefault) WithPayload(payload *models.Error) *DeleteWashDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete wash default response
func (o *DeleteWashDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWashDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *DeleteWashDefault) DeleteWashResponder() {}

type DeleteWashNotImplementedResponder struct {
	middleware.Responder
}

func (*DeleteWashNotImplementedResponder) DeleteWashResponder() {}

func DeleteWashNotImplemented() DeleteWashResponder {
	return &DeleteWashNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.DeleteWash has not yet been implemented",
		),
	}
}

type DeleteWashResponder interface {
	middleware.Responder
	DeleteWashResponder()
}
