// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PayResponse pay response
//
// swagger:model payResponse
type PayResponse struct {

	// order ID
	OrderID string `json:"orderID,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this pay response
func (m *PayResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pay response based on context it is used
func (m *PayResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PayResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PayResponse) UnmarshalBinary(b []byte) error {
	var res PayResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
