// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PayServer pay server
//
// swagger:model payServer
type PayServer struct {

	// url
	URL string `json:"url,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *PayServer) UnmarshalJSON(data []byte) error {
	var props struct {

		// url
		URL string `json:"url,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.URL = props.URL
	return nil
}

// Validate validates this pay server
func (m *PayServer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pay server based on context it is used
func (m *PayServer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PayServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PayServer) UnmarshalBinary(b []byte) error {
	var res PayServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
