// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Payment payment
//
// swagger:model Payment
type Payment struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// order Id
	OrderID string `json:"orderId,omitempty"`

	// post Id
	PostID string `json:"postId,omitempty"`

	// wash Id
	WashID string `json:"washId,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *Payment) UnmarshalJSON(data []byte) error {
	var props struct {

		// amount
		Amount int64 `json:"amount,omitempty"`

		// order Id
		OrderID string `json:"orderId,omitempty"`

		// post Id
		PostID string `json:"postId,omitempty"`

		// wash Id
		WashID string `json:"washId,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Amount = props.Amount
	m.OrderID = props.OrderID
	m.PostID = props.PostID
	m.WashID = props.WashID
	return nil
}

// Validate validates this payment
func (m *Payment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment based on context it is used
func (m *Payment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Payment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Payment) UnmarshalBinary(b []byte) error {
	var res Payment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
