// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentCancellation payment cancellation
//
// swagger:model PaymentCancellation
type PaymentCancellation struct {

	// order ID
	OrderID string `json:"orderID,omitempty"`

	// post ID
	PostID string `json:"postID,omitempty"`

	// wash ID
	WashID string `json:"washID,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *PaymentCancellation) UnmarshalJSON(data []byte) error {
	var props struct {

		// order ID
		OrderID string `json:"orderID,omitempty"`

		// post ID
		PostID string `json:"postID,omitempty"`

		// wash ID
		WashID string `json:"washID,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.OrderID = props.OrderID
	m.PostID = props.PostID
	m.WashID = props.WashID
	return nil
}

// Validate validates this payment cancellation
func (m *PaymentCancellation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment cancellation based on context it is used
func (m *PaymentCancellation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentCancellation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentCancellation) UnmarshalBinary(b []byte) error {
	var res PaymentCancellation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
