// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentResponse payment response
//
// swagger:model PaymentResponse
type PaymentResponse struct {

	// order ID
	OrderID string `json:"orderID,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *PaymentResponse) UnmarshalJSON(data []byte) error {
	var props struct {

		// order ID
		OrderID string `json:"orderID,omitempty"`

		// url
		URL string `json:"url,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.OrderID = props.OrderID
	m.URL = props.URL
	return nil
}

// Validate validates this payment response
func (m *PaymentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment response based on context it is used
func (m *PaymentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentResponse) UnmarshalBinary(b []byte) error {
	var res PaymentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
