// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WashUpdate wash update
//
// swagger:model WashUpdate
type WashUpdate struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// terminal key
	TerminalKey string `json:"terminalKey,omitempty"`

	// terminal password
	TerminalPassword string `json:"terminalPassword,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *WashUpdate) UnmarshalJSON(data []byte) error {
	var props struct {

		// description
		Description string `json:"description,omitempty"`

		// name
		Name string `json:"name,omitempty"`

		// terminal key
		TerminalKey string `json:"terminalKey,omitempty"`

		// terminal password
		TerminalPassword string `json:"terminalPassword,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Description = props.Description
	m.Name = props.Name
	m.TerminalKey = props.TerminalKey
	m.TerminalPassword = props.TerminalPassword
	return nil
}

// Validate validates this wash update
func (m *WashUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wash update based on context it is used
func (m *WashUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WashUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WashUpdate) UnmarshalBinary(b []byte) error {
	var res WashUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
