// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WashPostUpdate wash post update
//
// swagger:model WashPostUpdate
type WashPostUpdate struct {

	// id
	ID string `json:"id,omitempty"`

	// terminal key
	TerminalKey string `json:"terminalKey,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *WashPostUpdate) UnmarshalJSON(data []byte) error {
	var props struct {

		// id
		ID string `json:"id,omitempty"`

		// terminal key
		TerminalKey string `json:"terminalKey,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.ID = props.ID
	m.TerminalKey = props.TerminalKey
	return nil
}

// Validate validates this wash post update
func (m *WashPostUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wash post update based on context it is used
func (m *WashPostUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WashPostUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WashPostUpdate) UnmarshalBinary(b []byte) error {
	var res WashPostUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
