// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WashCreation wash creation
//
// swagger:model WashCreation
type WashCreation struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// group Id
	// Required: true
	// Format: uuid
	GroupID *strfmt.UUID `json:"groupId"`

	// name
	// Required: true
	Name *string `json:"name"`

	// terminal key
	// Required: true
	TerminalKey *string `json:"terminalKey"`

	// terminal password
	// Required: true
	TerminalPassword *string `json:"terminalPassword"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *WashCreation) UnmarshalJSON(data []byte) error {
	var props struct {

		// description
		// Required: true
		Description *string `json:"description"`

		// group Id
		// Required: true
		// Format: uuid
		GroupID *strfmt.UUID `json:"groupId"`

		// name
		// Required: true
		Name *string `json:"name"`

		// terminal key
		// Required: true
		TerminalKey *string `json:"terminalKey"`

		// terminal password
		// Required: true
		TerminalPassword *string `json:"terminalPassword"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Description = props.Description
	m.GroupID = props.GroupID
	m.Name = props.Name
	m.TerminalKey = props.TerminalKey
	m.TerminalPassword = props.TerminalPassword
	return nil
}

// Validate validates this wash creation
func (m *WashCreation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTerminalKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTerminalPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WashCreation) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *WashCreation) validateGroupID(formats strfmt.Registry) error {

	if err := validate.Required("groupId", "body", m.GroupID); err != nil {
		return err
	}

	if err := validate.FormatOf("groupId", "body", "uuid", m.GroupID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WashCreation) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *WashCreation) validateTerminalKey(formats strfmt.Registry) error {

	if err := validate.Required("terminalKey", "body", m.TerminalKey); err != nil {
		return err
	}

	return nil
}

func (m *WashCreation) validateTerminalPassword(formats strfmt.Registry) error {

	if err := validate.Required("terminalPassword", "body", m.TerminalPassword); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wash creation based on context it is used
func (m *WashCreation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WashCreation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WashCreation) UnmarshalBinary(b []byte) error {
	var res WashCreation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
