// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WashPostAdd wash post add
//
// swagger:model WashPostAdd
type WashPostAdd struct {

	// post ID
	PostID string `json:"postID,omitempty"`

	// server ID
	ServerID string `json:"serverID,omitempty"`

	// terminal key
	TerminalKey string `json:"terminalKey,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *WashPostAdd) UnmarshalJSON(data []byte) error {
	var props struct {

		// post ID
		PostID string `json:"postID,omitempty"`

		// server ID
		ServerID string `json:"serverID,omitempty"`

		// terminal key
		TerminalKey string `json:"terminalKey,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.PostID = props.PostID
	m.ServerID = props.ServerID
	m.TerminalKey = props.TerminalKey
	return nil
}

// Validate validates this wash post add
func (m *WashPostAdd) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wash post add based on context it is used
func (m *WashPostAdd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WashPostAdd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WashPostAdd) UnmarshalBinary(b []byte) error {
	var res WashPostAdd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
