// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WashPostDelete wash post delete
//
// swagger:model WashPostDelete
type WashPostDelete struct {

	// id
	ID string `json:"id,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *WashPostDelete) UnmarshalJSON(data []byte) error {
	var props struct {

		// id
		ID string `json:"id,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.ID = props.ID
	return nil
}

// Validate validates this wash post delete
func (m *WashPostDelete) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wash post delete based on context it is used
func (m *WashPostDelete) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WashPostDelete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WashPostDelete) UnmarshalBinary(b []byte) error {
	var res WashPostDelete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
