version: "3.2"

services:
  postgres:
    image: postgres:14.5
    container_name: wash_sbp_postgresql
    environment:
      POSTGRES_USER: sbp_admin
      POSTGRES_PASSWORD: sbp_admin_password
      POSTGRES_DB: postgres
    volumes:
      - sbp_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54327:5432"

  sbp_client:
    build:
      context: .
      dockerfile: Dockerfile
    image: sbp_client
    container_name: sbp_client
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  

volumes:
  sbp_postgres_data:
    driver: local