version: "3.2"

services:
  postgres:
    image: postgres:14.5
    container_name: wash_sbp_postgresql
    environment:
      POSTGRES_USER:  wash_sbp_admin
      POSTGRES_PASSWORD: wash_sbp_pass
      POSTGRES_DB: postgres
    volumes:
      - sbp_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54325:5432"

volumes:
  sbp_postgres_data:
    driver: local