version: "3.2"

services:
  postgres:
    image: postgres:14.5
    container_name: wash_sbp_postgresql
    environment:
      POSTGRES_USER:  wash_sbp_admin
      POSTGRES_PASSWORD: wash_sbp_pass
      POSTGRES_DB: postgres
    volumes:
      - sbp_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54327:5432"

volumes:
  sbp_postgres_data:
    driver: local

  # sbp_rabbit:
  #   container_name: sbp_rabbit
  #   hostname: 'sbp_rabbit'
  #   user: "rabbitmq"
  #   image: rabbitmq:3.11.8-management
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
    # volumes:
#       # - ./environment/certs/:/certs/
#       # - ./environment/rabbit/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./environment/rabbit/definitions.json:/etc/rabbitmq/definitions.json
#       - rabbitmq-data:/var/lib/rabbitmq
#       - rabbitmq-logs:/var/log/rabbitmq
#       - rabbitmq_conf:/etc/rabbitmq

# volumes:
#   rabbitmq-data:
#     driver: local
#   rabbitmq-logs:
#     driver: local
#   rabbitmq_conf:
#     driver: local
