// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseGetQr response get qr
//
// swagger:model ResponseGetQr
type ResponseGetQr struct {

	// data
	Data string `json:"Data,omitempty"`

	// details
	Details string `json:"Details,omitempty"`

	// error code
	ErrorCode string `json:"ErrorCode,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// order Id
	OrderID string `json:"OrderId,omitempty"`

	// payment Id
	PaymentID int64 `json:"PaymentId,omitempty"`

	// success
	Success bool `json:"Success,omitempty"`

	// terminal key
	TerminalKey string `json:"TerminalKey,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ResponseGetQr) UnmarshalJSON(data []byte) error {
	var props struct {

		// data
		Data string `json:"Data,omitempty"`

		// details
		Details string `json:"Details,omitempty"`

		// error code
		ErrorCode string `json:"ErrorCode,omitempty"`

		// message
		Message string `json:"Message,omitempty"`

		// order Id
		OrderID string `json:"OrderId,omitempty"`

		// payment Id
		PaymentID int64 `json:"PaymentId,omitempty"`

		// success
		Success bool `json:"Success,omitempty"`

		// terminal key
		TerminalKey string `json:"TerminalKey,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Data = props.Data
	m.Details = props.Details
	m.ErrorCode = props.ErrorCode
	m.Message = props.Message
	m.OrderID = props.OrderID
	m.PaymentID = props.PaymentID
	m.Success = props.Success
	m.TerminalKey = props.TerminalKey
	return nil
}

// Validate validates this response get qr
func (m *ResponseGetQr) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response get qr based on context it is used
func (m *ResponseGetQr) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseGetQr) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseGetQr) UnmarshalBinary(b []byte) error {
	var res ResponseGetQr
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
