swagger: "2.0"
info:
  description: "microservice for the sbp pay system of self-service car washes"
  title: wash-sbp
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
securityDefinitions:
  authKey:
    description: Session token inside Authorization header.
    type: apiKey
    in: header
    name: Authorization
security:
  - authKey: []
paths:

  /signup:
    post:
      tags:
        - wash
      security:
        - {}
      operationId: signup
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/FirebaseToken"

  /notification:
    post:
      tags:
        - wash
      security:
        - {}
      operationId: notification
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Notification"
      responses:
        200:
          description: OK
          schema:
            type: string
        400:
          description: Bad request
          schema:
            type: string
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"
            
  /health_check:
    get:
      tags:
        - Standard
      security:
        - {}
      operationId: healthCheck
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              ok:
                type: boolean

  /wash/{id}:
    get:
      tags:
        - wash
      security:
        - authKey: []
      operationId: getWash
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Wash"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"
        404:
          description: Wash not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

  /wash/:
    put:
      tags:
        - wash
      security:
        - authKey: []
      operationId: create
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashCreate"
      responses:
        200:
          description: Success creation
          schema:
            $ref: "#/definitions/Wash"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"
    patch:
      tags:
        - wash
      security:
        - authKey: []
      operationId: update
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashUpdate"
      responses:
        204:
          description: Success update
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"
        404:
          description: Wash not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - wash
      security:
        - authKey: []
      operationId: delete
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/WashDelete"
      responses:
        204:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"
        404:
          description: Wash not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

  /wash/list:
    get:
      tags:
        - wash
      security:
        - authKey: []
      operationId: list
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Pagination"
      responses:
        200:
          description: OK
          schema:
            type: array
            items: 
              $ref: "#/definitions/Wash"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"
        404:
          description: Wash not exists
          schema:
            $ref: "#/definitions/error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/error"

  /pay:
    post:
      tags:
        - wash
      security:
        - authKey: []
      operationId: pay
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Pay"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/payResponse"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"

  /cancel:
    post:
      tags:
        - wash
      security:
        - authKey: []
      operationId: cancel
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/cancel"
      responses:
        200:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/error"
        403:
          description: Access denied
          schema:
            $ref: "#/definitions/error"


definitions:
  cancel:
    type: object
    properties:
      washID:
        type: string
      postID:
        type: string
      orderID:
        type: string


  payResponse:
    type: object
    properties:
      url:
        type: string
      orderID:
        type: string

  Pay:
    type: object
    properties:
      washId:
        type: string
      postId:
        type: string
      orderId:
        type: string
      amount:
        type: integer

  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        description: Either same as HTTP Status Code OR >= 600.
        type: integer
        format: int32
      message:
        type: string

  Wash:
    type: object
    properties:
      id:
        type: string
      password:
        type: string
      name:
        type: string
      description:
        type: string
      terminal_key:
        type: string
      terminal_password:
        type: string

  WashCreate:
    properties:
      name:
        type: string
      description:
        type: string 
      terminal_key:
        type: string
      terminal_password:
        type: string
    required:
      - name

  WashUpdate:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      terminal_key:
        type: string
      terminal_password:
        type: string

  WashDelete:
    type: object
    properties:
      id:
        type: string
    required:
      - id

  Notification:
    type: object
    properties:
      TerminalKey:
        type: string
        description: Terminal key
      OrderId:
        type: string
        description: Order ID
      Success:
        type: boolean
        description: Indicates whether the payment was successful
      Status:
        type: string
        description: Payment status
      PaymentId:
        type: integer
        description: Payment ID
      ErrorCode:
        type: string
        description: Error code
      Amount:
        type: integer
        description: Payment amount
      Pan:
        type: string
        description: PAN (Primary Account Number)
      Token:
        type: string
        description: Payment token
      CardId:
        type: integer
        x-nullable: true
      ExpDate:
        type: string
        x-nullable: true

  Pagination:
    type: object
    properties: 
      limit:
        type: integer
        format: int64
        maximum: 100
      offset:
        type: integer
        format: int64

  FirebaseToken:
    type: object
    properties: 
      value:
        type: string
