// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Notification notification
//
// swagger:model Notification
type Notification struct {

	// amount
	Amount int64 `json:"Amount,omitempty"`

	// card Id
	CardID int64 `json:"CardId,omitempty"`

	// error code
	ErrorCode string `json:"ErrorCode,omitempty"`

	// exp date
	ExpDate string `json:"ExpDate,omitempty"`

	// order ID
	OrderID string `json:"OrderID,omitempty"`

	// pan
	Pan string `json:"Pan,omitempty"`

	// payment ID
	PaymentID string `json:"PaymentID,omitempty"`

	// status
	Status string `json:"Status,omitempty"`

	// success
	Success bool `json:"Success,omitempty"`

	// terminal key
	TerminalKey string `json:"TerminalKey,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *Notification) UnmarshalJSON(data []byte) error {
	var props struct {

		// amount
		Amount int64 `json:"Amount,omitempty"`

		// card Id
		CardID int64 `json:"CardId,omitempty"`

		// error code
		ErrorCode string `json:"ErrorCode,omitempty"`

		// exp date
		ExpDate string `json:"ExpDate,omitempty"`

		// order ID
		OrderID string `json:"OrderID,omitempty"`

		// pan
		Pan string `json:"Pan,omitempty"`

		// payment ID
		PaymentID string `json:"PaymentID,omitempty"`

		// status
		Status string `json:"Status,omitempty"`

		// success
		Success bool `json:"Success,omitempty"`

		// terminal key
		TerminalKey string `json:"TerminalKey,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Amount = props.Amount
	m.CardID = props.CardID
	m.ErrorCode = props.ErrorCode
	m.ExpDate = props.ExpDate
	m.OrderID = props.OrderID
	m.Pan = props.Pan
	m.PaymentID = props.PaymentID
	m.Status = props.Status
	m.Success = props.Success
	m.TerminalKey = props.TerminalKey
	return nil
}

// Validate validates this notification
func (m *Notification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notification based on context it is used
func (m *Notification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Notification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Notification) UnmarshalBinary(b []byte) error {
	var res Notification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
