// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FirebaseToken firebase token
//
// swagger:model FirebaseToken
type FirebaseToken struct {

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this firebase token
func (m *FirebaseToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this firebase token based on context it is used
func (m *FirebaseToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FirebaseToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FirebaseToken) UnmarshalBinary(b []byte) error {
	var res FirebaseToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
