// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pay pay
//
// swagger:model Pay
type Pay struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// post Id
	PostID string `json:"postId,omitempty"`

	// server Id
	ServerID string `json:"serverId,omitempty"`
}

// Validate validates this pay
func (m *Pay) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pay based on context it is used
func (m *Pay) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pay) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pay) UnmarshalBinary(b []byte) error {
	var res Pay
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
