// Code generated by go-swagger; DO NOT EDIT.

package wash

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"sbp/internal/logic/entities"
)

// GetWashHandlerFunc turns a function with the right signature into a get wash handler
type GetWashHandlerFunc func(GetWashParams, *entities.AuthExtended) GetWashResponder

// Handle executing the request and returning a response
func (fn GetWashHandlerFunc) Handle(params GetWashParams, principal *entities.AuthExtended) GetWashResponder {
	return fn(params, principal)
}

// GetWashHandler interface for that can handle valid get wash params
type GetWashHandler interface {
	Handle(GetWashParams, *entities.AuthExtended) GetWashResponder
}

// NewGetWash creates a new http.Handler for the get wash operation
func NewGetWash(ctx *middleware.Context, handler GetWashHandler) *GetWash {
	return &GetWash{Context: ctx, Handler: handler}
}

/*
	GetWash swagger:route GET /wash/{id} wash getWash

GetWash get wash API
*/
type GetWash struct {
	Context *middleware.Context
	Handler GetWashHandler
}

func (o *GetWash) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWashParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *entities.AuthExtended
	if uprinc != nil {
		principal = uprinc.(*entities.AuthExtended) // this is really a entities.AuthExtended, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
