// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/internal/pay-client/tinkoff/models"
)

// GetQrReader is a Reader for the GetQr structure.
type GetQrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetQrInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /GetQr] GetQr", response, response.Code())
	}
}

// NewGetQrOK creates a GetQrOK with default headers values
func NewGetQrOK() *GetQrOK {
	return &GetQrOK{}
}

/*
GetQrOK describes a response with status code 200, with default header values.

OK
*/
type GetQrOK struct {
	Payload *models.ResponseGetQr
}

// IsSuccess returns true when this get qr o k response has a 2xx status code
func (o *GetQrOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get qr o k response has a 3xx status code
func (o *GetQrOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get qr o k response has a 4xx status code
func (o *GetQrOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get qr o k response has a 5xx status code
func (o *GetQrOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get qr o k response a status code equal to that given
func (o *GetQrOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get qr o k response
func (o *GetQrOK) Code() int {
	return 200
}

func (o *GetQrOK) Error() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrOK  %+v", 200, o.Payload)
}

func (o *GetQrOK) String() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrOK  %+v", 200, o.Payload)
}

func (o *GetQrOK) GetPayload() *models.ResponseGetQr {
	return o.Payload
}

func (o *GetQrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseGetQr)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQrInternalServerError creates a GetQrInternalServerError with default headers values
func NewGetQrInternalServerError() *GetQrInternalServerError {
	return &GetQrInternalServerError{}
}

/*
GetQrInternalServerError describes a response with status code 500, with default header values.

error
*/
type GetQrInternalServerError struct {
}

// IsSuccess returns true when this get qr internal server error response has a 2xx status code
func (o *GetQrInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get qr internal server error response has a 3xx status code
func (o *GetQrInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get qr internal server error response has a 4xx status code
func (o *GetQrInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get qr internal server error response has a 5xx status code
func (o *GetQrInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get qr internal server error response a status code equal to that given
func (o *GetQrInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get qr internal server error response
func (o *GetQrInternalServerError) Code() int {
	return 500
}

func (o *GetQrInternalServerError) Error() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrInternalServerError ", 500)
}

func (o *GetQrInternalServerError) String() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrInternalServerError ", 500)
}

func (o *GetQrInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
