// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/internal/pay-client/tinkoff/models"
)

// InitReader is a Reader for the Init structure.
type InitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewInitInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /Init/] init", response, response.Code())
	}
}

// NewInitOK creates a InitOK with default headers values
func NewInitOK() *InitOK {
	return &InitOK{}
}

/*
InitOK describes a response with status code 200, with default header values.

OK
*/
type InitOK struct {
	Payload *models.ResponseInit
}

// IsSuccess returns true when this init o k response has a 2xx status code
func (o *InitOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this init o k response has a 3xx status code
func (o *InitOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this init o k response has a 4xx status code
func (o *InitOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this init o k response has a 5xx status code
func (o *InitOK) IsServerError() bool {
	return false
}

// IsCode returns true when this init o k response a status code equal to that given
func (o *InitOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the init o k response
func (o *InitOK) Code() int {
	return 200
}

func (o *InitOK) Error() string {
	return fmt.Sprintf("[POST /Init/][%d] initOK  %+v", 200, o.Payload)
}

func (o *InitOK) String() string {
	return fmt.Sprintf("[POST /Init/][%d] initOK  %+v", 200, o.Payload)
}

func (o *InitOK) GetPayload() *models.ResponseInit {
	return o.Payload
}

func (o *InitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseInit)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitInternalServerError creates a InitInternalServerError with default headers values
func NewInitInternalServerError() *InitInternalServerError {
	return &InitInternalServerError{}
}

/*
InitInternalServerError describes a response with status code 500, with default header values.

error
*/
type InitInternalServerError struct {
}

// IsSuccess returns true when this init internal server error response has a 2xx status code
func (o *InitInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this init internal server error response has a 3xx status code
func (o *InitInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this init internal server error response has a 4xx status code
func (o *InitInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this init internal server error response has a 5xx status code
func (o *InitInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this init internal server error response a status code equal to that given
func (o *InitInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the init internal server error response
func (o *InitInternalServerError) Code() int {
	return 500
}

func (o *InitInternalServerError) Error() string {
	return fmt.Sprintf("[POST /Init/][%d] initInternalServerError ", 500)
}

func (o *InitInternalServerError) String() string {
	return fmt.Sprintf("[POST /Init/][%d] initInternalServerError ", 500)
}

func (o *InitInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
