// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"sbp/internal/openapi/models"
)

// CancelOKCode is the HTTP code returned for type CancelOK
const CancelOKCode int = 200

/*
CancelOK OK

swagger:response cancelOK
*/
type CancelOK struct {
}

// NewCancelOK creates CancelOK with default headers values
func NewCancelOK() *CancelOK {

	return &CancelOK{}
}

// WriteResponse to the client
func (o *CancelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

func (o *CancelOK) CancelResponder() {}

// CancelBadRequestCode is the HTTP code returned for type CancelBadRequest
const CancelBadRequestCode int = 400

/*
CancelBadRequest Bad request

swagger:response cancelBadRequest
*/
type CancelBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCancelBadRequest creates CancelBadRequest with default headers values
func NewCancelBadRequest() *CancelBadRequest {

	return &CancelBadRequest{}
}

// WithPayload adds the payload to the cancel bad request response
func (o *CancelBadRequest) WithPayload(payload *models.Error) *CancelBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel bad request response
func (o *CancelBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *CancelBadRequest) CancelResponder() {}

type CancelNotImplementedResponder struct {
	middleware.Responder
}

func (*CancelNotImplementedResponder) CancelResponder() {}

func CancelNotImplemented() CancelResponder {
	return &CancelNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Cancel has not yet been implemented",
		),
	}
}

type CancelResponder interface {
	middleware.Responder
	CancelResponder()
}
