// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"sbp/openapi/models"
)

// SignupOKCode is the HTTP code returned for type SignupOK
const SignupOKCode int = 200

/*
SignupOK OK

swagger:response signupOK
*/
type SignupOK struct {

	/*
	  In: Body
	*/
	Payload *models.FirebaseToken `json:"body,omitempty"`
}

// NewSignupOK creates SignupOK with default headers values
func NewSignupOK() *SignupOK {

	return &SignupOK{}
}

// WithPayload adds the payload to the signup o k response
func (o *SignupOK) WithPayload(payload *models.FirebaseToken) *SignupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the signup o k response
func (o *SignupOK) SetPayload(payload *models.FirebaseToken) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *SignupOK) SignupResponder() {}

type SignupNotImplementedResponder struct {
	middleware.Responder
}

func (*SignupNotImplementedResponder) SignupResponder() {}

func SignupNotImplemented() SignupResponder {
	return &SignupNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Signup has not yet been implemented",
		),
	}
}

type SignupResponder interface {
	middleware.Responder
	SignupResponder()
}
