// Code generated by go-swagger; DO NOT EDIT.

package wash

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/openapi/models"
)

// SignupReader is a Reader for the Signup structure.
type SignupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /signup] signup", response, response.Code())
	}
}

// NewSignupOK creates a SignupOK with default headers values
func NewSignupOK() *SignupOK {
	return &SignupOK{}
}

/*
SignupOK describes a response with status code 200, with default header values.

OK
*/
type SignupOK struct {
	Payload *models.FirebaseToken
}

// IsSuccess returns true when this signup o k response has a 2xx status code
func (o *SignupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this signup o k response has a 3xx status code
func (o *SignupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this signup o k response has a 4xx status code
func (o *SignupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this signup o k response has a 5xx status code
func (o *SignupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this signup o k response a status code equal to that given
func (o *SignupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the signup o k response
func (o *SignupOK) Code() int {
	return 200
}

func (o *SignupOK) Error() string {
	return fmt.Sprintf("[POST /signup][%d] signupOK  %+v", 200, o.Payload)
}

func (o *SignupOK) String() string {
	return fmt.Sprintf("[POST /signup][%d] signupOK  %+v", 200, o.Payload)
}

func (o *SignupOK) GetPayload() *models.FirebaseToken {
	return o.Payload
}

func (o *SignupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FirebaseToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
