// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/tinkoffapi/models"
)

// CancelReader is a Reader for the Cancel structure.
type CancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCancelInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCancelOK creates a CancelOK with default headers values
func NewCancelOK() *CancelOK {
	return &CancelOK{}
}

/* CancelOK describes a response with status code 200, with default header values.

OK
*/
type CancelOK struct {
	Payload *models.ResponseCancel
}

func (o *CancelOK) Error() string {
	return fmt.Sprintf("[POST /Cancel][%d] cancelOK  %+v", 200, o.Payload)
}
func (o *CancelOK) GetPayload() *models.ResponseCancel {
	return o.Payload
}

func (o *CancelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseCancel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCancelInternalServerError creates a CancelInternalServerError with default headers values
func NewCancelInternalServerError() *CancelInternalServerError {
	return &CancelInternalServerError{}
}

/* CancelInternalServerError describes a response with status code 500, with default header values.

error
*/
type CancelInternalServerError struct {
}

func (o *CancelInternalServerError) Error() string {
	return fmt.Sprintf("[POST /Cancel][%d] cancelInternalServerError ", 500)
}

func (o *CancelInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
