// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/tinkoffapi/models"
)

// GetQrReader is a Reader for the GetQr structure.
type GetQrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetQrInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetQrOK creates a GetQrOK with default headers values
func NewGetQrOK() *GetQrOK {
	return &GetQrOK{}
}

/* GetQrOK describes a response with status code 200, with default header values.

OK
*/
type GetQrOK struct {
	Payload *models.ResponseGetQr
}

func (o *GetQrOK) Error() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrOK  %+v", 200, o.Payload)
}
func (o *GetQrOK) GetPayload() *models.ResponseGetQr {
	return o.Payload
}

func (o *GetQrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseGetQr)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQrInternalServerError creates a GetQrInternalServerError with default headers values
func NewGetQrInternalServerError() *GetQrInternalServerError {
	return &GetQrInternalServerError{}
}

/* GetQrInternalServerError describes a response with status code 500, with default header values.

error
*/
type GetQrInternalServerError struct {
}

func (o *GetQrInternalServerError) Error() string {
	return fmt.Sprintf("[POST /GetQr][%d] getQrInternalServerError ", 500)
}

func (o *GetQrInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
