// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"sbp/tinkoffapi/models"
)

// NewInitParams creates a new InitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInitParams() *InitParams {
	return &InitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInitParamsWithTimeout creates a new InitParams object
// with the ability to set a timeout on a request.
func NewInitParamsWithTimeout(timeout time.Duration) *InitParams {
	return &InitParams{
		timeout: timeout,
	}
}

// NewInitParamsWithContext creates a new InitParams object
// with the ability to set a context for a request.
func NewInitParamsWithContext(ctx context.Context) *InitParams {
	return &InitParams{
		Context: ctx,
	}
}

// NewInitParamsWithHTTPClient creates a new InitParams object
// with the ability to set a custom HTTPClient for a request.
func NewInitParamsWithHTTPClient(client *http.Client) *InitParams {
	return &InitParams{
		HTTPClient: client,
	}
}

/* InitParams contains all the parameters to send to the API endpoint
   for the init operation.

   Typically these are written to a http.Request.
*/
type InitParams struct {

	// Body.
	Body *models.Init

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InitParams) WithDefaults() *InitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the init params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the init params
func (o *InitParams) WithTimeout(timeout time.Duration) *InitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the init params
func (o *InitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the init params
func (o *InitParams) WithContext(ctx context.Context) *InitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the init params
func (o *InitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the init params
func (o *InitParams) WithHTTPClient(client *http.Client) *InitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the init params
func (o *InitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the init params
func (o *InitParams) WithBody(body *models.Init) *InitParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the init params
func (o *InitParams) SetBody(body *models.Init) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *InitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
