// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Cancel(params *CancelParams, opts ...ClientOption) (*CancelOK, error)

	GetQr(params *GetQrParams, opts ...ClientOption) (*GetQrOK, error)

	Init(params *InitParams, opts ...ClientOption) (*InitOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Cancel Cancel pay from Tinkoff
*/
func (a *Client) Cancel(params *CancelParams, opts ...ClientOption) (*CancelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCancelParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "Cancel",
		Method:             "POST",
		PathPattern:        "/Cancel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CancelReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CancelOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Cancel: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetQr Get Qr code from Tinkoff
*/
func (a *Client) GetQr(params *GetQrParams, opts ...ClientOption) (*GetQrOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetQrParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetQr",
		Method:             "POST",
		PathPattern:        "/GetQr",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetQrReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetQrOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetQr: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Init init tinkoff operation
*/
func (a *Client) Init(params *InitParams, opts ...ClientOption) (*InitOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInitParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "init",
		Method:             "POST",
		PathPattern:        "/Init/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &InitReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*InitOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for init: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
