// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNewExchangeReader is a Reader for the CreateNewExchange structure.
type CreateNewExchangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNewExchangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNewExchangeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewCreateNewExchangeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateNewExchangeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateNewExchangeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/exchanges/{vhost}/{exchange_name}] createNewExchange", response, response.Code())
	}
}

// NewCreateNewExchangeCreated creates a CreateNewExchangeCreated with default headers values
func NewCreateNewExchangeCreated() *CreateNewExchangeCreated {
	return &CreateNewExchangeCreated{}
}

/*
CreateNewExchangeCreated describes a response with status code 201, with default header values.

ok
*/
type CreateNewExchangeCreated struct {
}

// IsSuccess returns true when this create new exchange created response has a 2xx status code
func (o *CreateNewExchangeCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create new exchange created response has a 3xx status code
func (o *CreateNewExchangeCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new exchange created response has a 4xx status code
func (o *CreateNewExchangeCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new exchange created response has a 5xx status code
func (o *CreateNewExchangeCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create new exchange created response a status code equal to that given
func (o *CreateNewExchangeCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create new exchange created response
func (o *CreateNewExchangeCreated) Code() int {
	return 201
}

func (o *CreateNewExchangeCreated) Error() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeCreated ", 201)
}

func (o *CreateNewExchangeCreated) String() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeCreated ", 201)
}

func (o *CreateNewExchangeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNewExchangeNoContent creates a CreateNewExchangeNoContent with default headers values
func NewCreateNewExchangeNoContent() *CreateNewExchangeNoContent {
	return &CreateNewExchangeNoContent{}
}

/*
CreateNewExchangeNoContent describes a response with status code 204, with default header values.

ok
*/
type CreateNewExchangeNoContent struct {
}

// IsSuccess returns true when this create new exchange no content response has a 2xx status code
func (o *CreateNewExchangeNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create new exchange no content response has a 3xx status code
func (o *CreateNewExchangeNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new exchange no content response has a 4xx status code
func (o *CreateNewExchangeNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new exchange no content response has a 5xx status code
func (o *CreateNewExchangeNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this create new exchange no content response a status code equal to that given
func (o *CreateNewExchangeNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the create new exchange no content response
func (o *CreateNewExchangeNoContent) Code() int {
	return 204
}

func (o *CreateNewExchangeNoContent) Error() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeNoContent ", 204)
}

func (o *CreateNewExchangeNoContent) String() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeNoContent ", 204)
}

func (o *CreateNewExchangeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNewExchangeBadRequest creates a CreateNewExchangeBadRequest with default headers values
func NewCreateNewExchangeBadRequest() *CreateNewExchangeBadRequest {
	return &CreateNewExchangeBadRequest{}
}

/*
CreateNewExchangeBadRequest describes a response with status code 400, with default header values.

bad request
*/
type CreateNewExchangeBadRequest struct {
}

// IsSuccess returns true when this create new exchange bad request response has a 2xx status code
func (o *CreateNewExchangeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new exchange bad request response has a 3xx status code
func (o *CreateNewExchangeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new exchange bad request response has a 4xx status code
func (o *CreateNewExchangeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new exchange bad request response has a 5xx status code
func (o *CreateNewExchangeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create new exchange bad request response a status code equal to that given
func (o *CreateNewExchangeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create new exchange bad request response
func (o *CreateNewExchangeBadRequest) Code() int {
	return 400
}

func (o *CreateNewExchangeBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeBadRequest ", 400)
}

func (o *CreateNewExchangeBadRequest) String() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeBadRequest ", 400)
}

func (o *CreateNewExchangeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNewExchangeInternalServerError creates a CreateNewExchangeInternalServerError with default headers values
func NewCreateNewExchangeInternalServerError() *CreateNewExchangeInternalServerError {
	return &CreateNewExchangeInternalServerError{}
}

/*
CreateNewExchangeInternalServerError describes a response with status code 500, with default header values.

error
*/
type CreateNewExchangeInternalServerError struct {
}

// IsSuccess returns true when this create new exchange internal server error response has a 2xx status code
func (o *CreateNewExchangeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new exchange internal server error response has a 3xx status code
func (o *CreateNewExchangeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new exchange internal server error response has a 4xx status code
func (o *CreateNewExchangeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new exchange internal server error response has a 5xx status code
func (o *CreateNewExchangeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create new exchange internal server error response a status code equal to that given
func (o *CreateNewExchangeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create new exchange internal server error response
func (o *CreateNewExchangeInternalServerError) Code() int {
	return 500
}

func (o *CreateNewExchangeInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeInternalServerError ", 500)
}

func (o *CreateNewExchangeInternalServerError) String() string {
	return fmt.Sprintf("[PUT /api/exchanges/{vhost}/{exchange_name}][%d] createNewExchangeInternalServerError ", 500)
}

func (o *CreateNewExchangeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
