// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWashPostParams creates a new GetWashPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWashPostParams() *GetWashPostParams {
	return &GetWashPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWashPostParamsWithTimeout creates a new GetWashPostParams object
// with the ability to set a timeout on a request.
func NewGetWashPostParamsWithTimeout(timeout time.Duration) *GetWashPostParams {
	return &GetWashPostParams{
		timeout: timeout,
	}
}

// NewGetWashPostParamsWithContext creates a new GetWashPostParams object
// with the ability to set a context for a request.
func NewGetWashPostParamsWithContext(ctx context.Context) *GetWashPostParams {
	return &GetWashPostParams{
		Context: ctx,
	}
}

// NewGetWashPostParamsWithHTTPClient creates a new GetWashPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWashPostParamsWithHTTPClient(client *http.Client) *GetWashPostParams {
	return &GetWashPostParams{
		HTTPClient: client,
	}
}

/*
GetWashPostParams contains all the parameters to send to the API endpoint

	for the get wash post operation.

	Typically these are written to a http.Request.
*/
type GetWashPostParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get wash post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWashPostParams) WithDefaults() *GetWashPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get wash post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWashPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get wash post params
func (o *GetWashPostParams) WithTimeout(timeout time.Duration) *GetWashPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get wash post params
func (o *GetWashPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get wash post params
func (o *GetWashPostParams) WithContext(ctx context.Context) *GetWashPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get wash post params
func (o *GetWashPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get wash post params
func (o *GetWashPostParams) WithHTTPClient(client *http.Client) *GetWashPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get wash post params
func (o *GetWashPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get wash post params
func (o *GetWashPostParams) WithID(id string) *GetWashPostParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get wash post params
func (o *GetWashPostParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetWashPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
