// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/openapi/models"
)

// GetWashPostReader is a Reader for the GetWashPost structure.
type GetWashPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWashPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWashPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetWashPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetWashPostNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetWashPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWashPostOK creates a GetWashPostOK with default headers values
func NewGetWashPostOK() *GetWashPostOK {
	return &GetWashPostOK{}
}

/*
GetWashPostOK describes a response with status code 200, with default header values.

OK
*/
type GetWashPostOK struct {
	Payload *models.WashPost
}

// IsSuccess returns true when this get wash post o k response has a 2xx status code
func (o *GetWashPostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get wash post o k response has a 3xx status code
func (o *GetWashPostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get wash post o k response has a 4xx status code
func (o *GetWashPostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get wash post o k response has a 5xx status code
func (o *GetWashPostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get wash post o k response a status code equal to that given
func (o *GetWashPostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get wash post o k response
func (o *GetWashPostOK) Code() int {
	return 200
}

func (o *GetWashPostOK) Error() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostOK  %+v", 200, o.Payload)
}

func (o *GetWashPostOK) String() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostOK  %+v", 200, o.Payload)
}

func (o *GetWashPostOK) GetPayload() *models.WashPost {
	return o.Payload
}

func (o *GetWashPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WashPost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWashPostBadRequest creates a GetWashPostBadRequest with default headers values
func NewGetWashPostBadRequest() *GetWashPostBadRequest {
	return &GetWashPostBadRequest{}
}

/*
GetWashPostBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetWashPostBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get wash post bad request response has a 2xx status code
func (o *GetWashPostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get wash post bad request response has a 3xx status code
func (o *GetWashPostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get wash post bad request response has a 4xx status code
func (o *GetWashPostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get wash post bad request response has a 5xx status code
func (o *GetWashPostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get wash post bad request response a status code equal to that given
func (o *GetWashPostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get wash post bad request response
func (o *GetWashPostBadRequest) Code() int {
	return 400
}

func (o *GetWashPostBadRequest) Error() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostBadRequest  %+v", 400, o.Payload)
}

func (o *GetWashPostBadRequest) String() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostBadRequest  %+v", 400, o.Payload)
}

func (o *GetWashPostBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetWashPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWashPostNotFound creates a GetWashPostNotFound with default headers values
func NewGetWashPostNotFound() *GetWashPostNotFound {
	return &GetWashPostNotFound{}
}

/*
GetWashPostNotFound describes a response with status code 404, with default header values.

WashServer not exists
*/
type GetWashPostNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get wash post not found response has a 2xx status code
func (o *GetWashPostNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get wash post not found response has a 3xx status code
func (o *GetWashPostNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get wash post not found response has a 4xx status code
func (o *GetWashPostNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get wash post not found response has a 5xx status code
func (o *GetWashPostNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get wash post not found response a status code equal to that given
func (o *GetWashPostNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get wash post not found response
func (o *GetWashPostNotFound) Code() int {
	return 404
}

func (o *GetWashPostNotFound) Error() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostNotFound  %+v", 404, o.Payload)
}

func (o *GetWashPostNotFound) String() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostNotFound  %+v", 404, o.Payload)
}

func (o *GetWashPostNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetWashPostNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWashPostInternalServerError creates a GetWashPostInternalServerError with default headers values
func NewGetWashPostInternalServerError() *GetWashPostInternalServerError {
	return &GetWashPostInternalServerError{}
}

/*
GetWashPostInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetWashPostInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get wash post internal server error response has a 2xx status code
func (o *GetWashPostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get wash post internal server error response has a 3xx status code
func (o *GetWashPostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get wash post internal server error response has a 4xx status code
func (o *GetWashPostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get wash post internal server error response has a 5xx status code
func (o *GetWashPostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get wash post internal server error response a status code equal to that given
func (o *GetWashPostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get wash post internal server error response
func (o *GetWashPostInternalServerError) Code() int {
	return 500
}

func (o *GetWashPostInternalServerError) Error() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostInternalServerError  %+v", 500, o.Payload)
}

func (o *GetWashPostInternalServerError) String() string {
	return fmt.Sprintf("[GET /wash-post/{id}][%d] getWashPostInternalServerError  %+v", 500, o.Payload)
}

func (o *GetWashPostInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetWashPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
