// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"sbp/openapi/models"
)

// PostDeleteReader is a Reader for the PostDelete structure.
type PostDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPostDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDeleteNoContent creates a PostDeleteNoContent with default headers values
func NewPostDeleteNoContent() *PostDeleteNoContent {
	return &PostDeleteNoContent{}
}

/*
PostDeleteNoContent describes a response with status code 204, with default header values.

OK
*/
type PostDeleteNoContent struct {
}

// IsSuccess returns true when this post delete no content response has a 2xx status code
func (o *PostDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post delete no content response has a 3xx status code
func (o *PostDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post delete no content response has a 4xx status code
func (o *PostDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post delete no content response has a 5xx status code
func (o *PostDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post delete no content response a status code equal to that given
func (o *PostDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the post delete no content response
func (o *PostDeleteNoContent) Code() int {
	return 204
}

func (o *PostDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteNoContent ", 204)
}

func (o *PostDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteNoContent ", 204)
}

func (o *PostDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDeleteBadRequest creates a PostDeleteBadRequest with default headers values
func NewPostDeleteBadRequest() *PostDeleteBadRequest {
	return &PostDeleteBadRequest{}
}

/*
PostDeleteBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PostDeleteBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this post delete bad request response has a 2xx status code
func (o *PostDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post delete bad request response has a 3xx status code
func (o *PostDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post delete bad request response has a 4xx status code
func (o *PostDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post delete bad request response has a 5xx status code
func (o *PostDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post delete bad request response a status code equal to that given
func (o *PostDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post delete bad request response
func (o *PostDeleteBadRequest) Code() int {
	return 400
}

func (o *PostDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *PostDeleteBadRequest) String() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *PostDeleteBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDeleteNotFound creates a PostDeleteNotFound with default headers values
func NewPostDeleteNotFound() *PostDeleteNotFound {
	return &PostDeleteNotFound{}
}

/*
PostDeleteNotFound describes a response with status code 404, with default header values.

WashServer not exists
*/
type PostDeleteNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this post delete not found response has a 2xx status code
func (o *PostDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post delete not found response has a 3xx status code
func (o *PostDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post delete not found response has a 4xx status code
func (o *PostDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post delete not found response has a 5xx status code
func (o *PostDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post delete not found response a status code equal to that given
func (o *PostDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post delete not found response
func (o *PostDeleteNotFound) Code() int {
	return 404
}

func (o *PostDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteNotFound  %+v", 404, o.Payload)
}

func (o *PostDeleteNotFound) String() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteNotFound  %+v", 404, o.Payload)
}

func (o *PostDeleteNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDeleteInternalServerError creates a PostDeleteInternalServerError with default headers values
func NewPostDeleteInternalServerError() *PostDeleteInternalServerError {
	return &PostDeleteInternalServerError{}
}

/*
PostDeleteInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostDeleteInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this post delete internal server error response has a 2xx status code
func (o *PostDeleteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post delete internal server error response has a 3xx status code
func (o *PostDeleteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post delete internal server error response has a 4xx status code
func (o *PostDeleteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post delete internal server error response has a 5xx status code
func (o *PostDeleteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post delete internal server error response a status code equal to that given
func (o *PostDeleteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post delete internal server error response
func (o *PostDeleteInternalServerError) Code() int {
	return 500
}

func (o *PostDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *PostDeleteInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /wash-post/][%d] postDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *PostDeleteInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
