// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"sbp/openapi/models"
)

// NewPostDeleteParams creates a new PostDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDeleteParams() *PostDeleteParams {
	return &PostDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDeleteParamsWithTimeout creates a new PostDeleteParams object
// with the ability to set a timeout on a request.
func NewPostDeleteParamsWithTimeout(timeout time.Duration) *PostDeleteParams {
	return &PostDeleteParams{
		timeout: timeout,
	}
}

// NewPostDeleteParamsWithContext creates a new PostDeleteParams object
// with the ability to set a context for a request.
func NewPostDeleteParamsWithContext(ctx context.Context) *PostDeleteParams {
	return &PostDeleteParams{
		Context: ctx,
	}
}

// NewPostDeleteParamsWithHTTPClient creates a new PostDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDeleteParamsWithHTTPClient(client *http.Client) *PostDeleteParams {
	return &PostDeleteParams{
		HTTPClient: client,
	}
}

/*
PostDeleteParams contains all the parameters to send to the API endpoint

	for the post delete operation.

	Typically these are written to a http.Request.
*/
type PostDeleteParams struct {

	// Body.
	Body *models.WashPostDelete

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDeleteParams) WithDefaults() *PostDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post delete params
func (o *PostDeleteParams) WithTimeout(timeout time.Duration) *PostDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post delete params
func (o *PostDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post delete params
func (o *PostDeleteParams) WithContext(ctx context.Context) *PostDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post delete params
func (o *PostDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post delete params
func (o *PostDeleteParams) WithHTTPClient(client *http.Client) *PostDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post delete params
func (o *PostDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post delete params
func (o *PostDeleteParams) WithBody(body *models.WashPostDelete) *PostDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post delete params
func (o *PostDeleteParams) SetBody(body *models.WashPostDelete) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
