// Code generated by go-swagger; DO NOT EDIT.

package wash_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"sbp/openapi/models"
)

// NewPostAddParams creates a new PostAddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAddParams() *PostAddParams {
	return &PostAddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAddParamsWithTimeout creates a new PostAddParams object
// with the ability to set a timeout on a request.
func NewPostAddParamsWithTimeout(timeout time.Duration) *PostAddParams {
	return &PostAddParams{
		timeout: timeout,
	}
}

// NewPostAddParamsWithContext creates a new PostAddParams object
// with the ability to set a context for a request.
func NewPostAddParamsWithContext(ctx context.Context) *PostAddParams {
	return &PostAddParams{
		Context: ctx,
	}
}

// NewPostAddParamsWithHTTPClient creates a new PostAddParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAddParamsWithHTTPClient(client *http.Client) *PostAddParams {
	return &PostAddParams{
		HTTPClient: client,
	}
}

/*
PostAddParams contains all the parameters to send to the API endpoint

	for the post add operation.

	Typically these are written to a http.Request.
*/
type PostAddParams struct {

	// Body.
	Body *models.WashPostAdd

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAddParams) WithDefaults() *PostAddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post add params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post add params
func (o *PostAddParams) WithTimeout(timeout time.Duration) *PostAddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post add params
func (o *PostAddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post add params
func (o *PostAddParams) WithContext(ctx context.Context) *PostAddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post add params
func (o *PostAddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post add params
func (o *PostAddParams) WithHTTPClient(client *http.Client) *PostAddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post add params
func (o *PostAddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post add params
func (o *PostAddParams) WithBody(body *models.WashPostAdd) *PostAddParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post add params
func (o *PostAddParams) SetBody(body *models.WashPostAdd) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
