// Code generated by go-swagger; DO NOT EDIT.

// Package restapi wash-sbp
//
//	microservice for the sbp system of self-service car washes
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
